Adding command to export to `index.html`
LiveDuo/destack-starter pull request #1
Opened 2021-11-29 18:15 UTC by beersweetpicklepanda

Hey @LiveDuo,

I don't understand `next.js`, but I needed the project to have `index.html` that other web servers could run it. 

I found `next.js` can leverage the `export` command, and it seems to be working fine. Let me know your thoughts.

2021-11-29 20:25 UTC, LiveDuo commented on README.md
> +If you need to deploy it with `index.html`, export it with:
Export the project to static HTML with:

2021-11-29 22:04 UTC, LiveDuo commented on README.md
> +If you need to deploy it with `index.html`, export it with:
```suggestion
Export the project to static HTML with:
```

2021-11-29 22:04 UTC, LiveDuo commented on README.md
> +`index.html` will be exported in the `out` directory
```suggestion
This will export `index.html` to the `out` directory.
```

2021-11-29 22:06 UTC, LiveDuo requested changes
We can have `next export` command. Just some minor grammatical comments.

2021-11-30 12:58 UTC, beersweetpicklepanda commented
Done, thanks for the correction! 👍

2021-11-30 15:25 UTC, merged